from root.GIT.yahboom_rdk_x3_robot.sunriseRobot.app_SunriseRobot.robot_body import RobotBody


robot_body = RobotBody(verbose=2)
robot_body.create_receive_threading()
robot_body.set_beep(100)
robot_body.set_beep(100)
robot_body.set_beep(100)
robot_body.set_beep(100)
robot_body.set_beep(100)
robot_body.set_beep(100)
robot_body.set_beep(300)
robot_body.set_beep(300)
robot_body.set_beep(100)
robot_body.set_beep(100)
robot_body.set_beep(100)
robot_body.set_beep(100)
robot_body.set_beep(100)
robot_body.set_beep(100)
robot_body.set_beep(300)
robot_body.set_beep(300)
robot_body.set_beep(100)
robot_body.set_beep(100)
robot_body.set_beep(100)
robot_body.set_beep(100)
robot_body.set_beep(100)
robot_body.set_beep(100)
robot_body.set_beep(300)
robot_body.set_beep(100)
robot_body.set_beep(100)
robot_body.set_beep(100)
robot_body.set_beep(400)
