verbose: True
save_images: True

robot_kwargs:
  speed_coefficient: 0.7

camera_kwargs:
  image_orientation: 0
  video_capture_kwargs:
    pipe_id: 1
    video_index: -1
    fps: 5
  #    width: 1920
  #    height: 1080
    width: 640
    height: 480
  #    raw_width: 1920
  #    raw_height: 1080

tracker_kwargs:
  model_name: yolov5nu.pt
  model_folder: models/
