verbose: False
steer_threshold: 0.05
save_images: True

camera_kwargs:
  video_capture_kwargs:
    pipe_id: 1
    video_index: -1
    fps: 5
  #    width: 1920
  #    height: 1080
    width: 640
    height: 480
  #    raw_width: 1920
  #    raw_height: 1080
