verbose: 0
# for autonomous mode only
steer_threshold: 0.25
angular_speed_range: [1.0, 2.0]
save_images: True
use_gpio_led: Ture
think_steps_if_no_target: 3

camera_kwargs:
  video_capture_kwargs:
    pipe_id: 1
    video_index: -1
    fps: 2
  #    width: 1920
  #    height: 1080
    width: 640
    height: 480
#    width: 1280
#    height: 960
  #    raw_width: 1920
  #    raw_height: 1080
