verbose: False
# for autonomous mode only
steer_threshold: 0.2
angular_speed_range: [1, 2]
save_images: False

camera_kwargs:
  video_capture_kwargs:
    pipe_id: 1
    video_index: -1
    fps: 1
  #    width: 1920
  #    height: 1080
    width: 640
    height: 480
#    width: 1280
#    height: 960
  #    raw_width: 1920
  #    raw_height: 1080
