verbose: 0
# for autonomous mode only
steer_threshold: 0.3
angular_speed_range: [1.0, 2.0]
save_images: False
use_gpio_led: True
think_steps_if_no_target: 3

camera_kwargs:
  index: 8
  fps: 10
  buffer_size: 1
  width: 640
  height: 480
#  width: 1280
#  height: 960
#  width: 1920
#  height: 1080