verbose: 0

# the speed of the arm is a proportion of the wheel speed. This is used when the user is moving the arm with
# forward kinematics
arm_speed_proportion_fk: 2
arm_speed_proportion_ik: 0.5
# This is used when setting an arbitrary position for the arm. Allowed range is [0, 2000], with 0 beeing the maximum
# speed and 2000 being the minimum speed. This range is used to convert the current robot speed to the arm speed.
# arm_automated_speed=0 is too fast, so the maximum allowed is higher (which mean a lower speed)
arm_automated_speed: [600, 2000]