loop_sleep_time: 0.02  # seconds

beep_time: 50  # milliseconds

# lidar parameters
lidar_kwargs:
  topic_name: scan
  queue_size: 3
  response_dist: 0.8
  sector_angle: 20
  scan_expiration_time: 0.5
# if the robot is closer than this distance to an obstacle, it will stop
# it is a range because it is dynamically calculated based on the current speed
min_allowed_distance: [0.2, 0.4]