loop_sleep_time: 0.02  # seconds

# milliseconds
beep_time: 50

# lidar parameters
lidar_kwargs:
  topic_name: scan
  queue_size: 3
  response_dist: 0.8
  sector_angle: 20
  scan_expiration_time: 0.5
# if the robot is closer than this distance to an obstacle, it will stop
# it is a range because it is dynamically calculated based on the current speed
min_allowed_distance: [0.2, 0.4]

# arm parameters
# how much the arm servos can rotate in a single loop iteration (in degrees)
max_degree_change: 0.1
# arm.current_angle_list is an estimate of the arm angles. Every n loop iterations
# the arm angles are updated to the real angles. This is done to avoid too frequent updates of the servos.
arm_update_frequency: 1