loop_sleep_time: 0.02  # seconds

# lidar parameter
# if the robot is closer than this distance to an obstacle, it will stop
# it is a range because it is dynamically calculated based on the current speed
min_allowed_distance: [0.2, 0.4]