verbose: 2
# 0: errors only
# 1: errors and important information
# 2: more information
# 3: debug

# serial parameters
com: /dev/ttyUSB0
#com: /dev/myserial
baud_rate: 115200

#camera_type: internal
camera_type: usb_v1
#camera_type: usb_v2