verbose: 0
hotspot_ip: 192.168.8.88
#speed_coefficient represent both the maximum wheel speed and the arm sensibility
# 1) maximum wheel speed [0.1, 1]
#   all controller inputs are scaled according to this value
# 2) arm control sensibility [0.1, 1]
#   how much a controller input changes the position of the arm
speed_coefficient: 0.5
steer_speed_proportion: 5
arm_speed_proportion: 2.5
tracking_target_list: [person, cat, orange, remote, mouse]

# the user needs to keep a controller button pressed at least this time for certain actions to occur (seconds)
button_press_required_time: 1.8