verbose: 0

#ReSpeaker 4-Mic Array v2.0 identification numbers
vendor_id: 0x2886
product_id: 0x0018

# if the robot is almost aligned with the target (angle < steer_threshold_1)
#     the robot will advance
# if the robot is almost somewhat aligned with the target (steer_threshold_1 < angle < steer_threshold_2)
#     the robot will steer AND advance
# if the robot is not aligned with the target (angle > steer_threshold_2)
#     the robot will steer
steer_threshold_1: 0.25
steer_threshold_2: 0.4
