verbose: 0
use_gpio_led: True

#ReSpeaker 4-Mic Array v2.0 identification numbers
vendor_id: 0x2886
product_id: 0x0018

move_duration: 0.2

# min and max forward speed of the robot
forward_speed_range: [0, 0.8]
# min and max turning speed of the robot
angular_speed_range: [0, 3.6]

# the forward direction of the microphone array (DOA=0) relative to the robot's forward direction (see
# microphone_orientation.png)
microphone_robot_angle: 64.0

# if the target is behind or almost behind the robot (angle => turn_only_angle), the robot will only rotate in place
# if the robot is almost somewhat aligned with the target (0 <= angle < turn_only_angle), the robot will steer
#  AND advance. the proportion between steering and advancing is determined by the angle
turn_only_angle: 50.0

# if True, the robot will ignore all sounds that come from the back of the microphone array
# this will remove the sounds of the robot, but also the sounds of the target if it is behind the robot
ignore_self_noise: False
# angle (in degrees) after which the sound is considered to be coming from the back of the robot
ignore_angle: 140.0